### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by springmeyer** [springmeyer/learn-c#1]
Imagining:
- [ ] Add examples showing what the preprocessor does and how it is involved (`cpp` / `gcc -E`)
- [ ] Add C++ files that mirror the C examples, but show the most basic yet subtle differences with C++
- [ ] Think through an organization system of directories of examples that will scale and be easy to navigate
- [ ] Provide links to learning about builds system like [gyp](https://github.com/springmeyer/hello-gyp)

**Comment by jakepruitt** [comment]
In terms of organization, I'm a big fan of the nodeschool.io workshops, especially the format of https://github.com/workshopper/goingnative, which delves into node-related C++. May not be perfectly suited for a c-only system, but could provide inspiration around scalable organization. :smile:

**Comment by mapsam** [comment]
Would be great to highlight the differences between relative file path `#include "file.hpp"` statements and paths relative to the `-I` path `#include <file.hpp>`.
